if: branch = dev

language: node_js
node_js:
  - "12.13.0"

cache:
  directories:
    - backend/node_modules

script:
  - npm install -g serverless
  - cd backend
  - npm install
  - npx sls deploy -v
  
branches:
  only:
  - dev